[package]
name = "nu_plugin_audio"
version = "0.2.9"
edition = "2021"
description = "A nushell plugin to make and play sounds"
readme = "README.md"
homepage = "https://github.com/SuaveIV/nu_plugin_audio"
repository = "https://github.com/SuaveIV/nu_plugin_audio"
license = "MIT"
keywords = [
  "audio",
  "mp3",
  "nushell",
  "player",
  "plugin",
]

[package.metadata]
authors-file = "AUTHORS"

[dependencies]
chrono = "0.4.45"
env_logger = "0.11"
log = "0.4"

[dependencies.crossterm]
version = "0.29"

[dependencies.lofty]
version = "0.24"

[dependencies.nu-plugin]
version = "0.114.1"

[dependencies.nu-protocol]
version = "0.114.1"
features = ["plugin"]

[dependencies.rodio]
version = "0.22.1"
default-features = false

[dependencies.unicode-width]
version = "0.2"

[features]
default = [
  "rodio/64bit",
  "rodio/dither",
  "rodio/experimental",
  "rodio/playback",
  "rodio/recording",
  "rodio/symphonia-all",
  "rodio/symphonia-simd",
  "rodio/wav_output",
]

lite = [
  "rodio/flac",
  "rodio/playback",
  "rodio/symphonia-mp3",
  "rodio/vorbis",
  "rodio/wav",
]

# Retained as an alias for backwards compatibility
all-decoders = ["default"]

[profile.release]
opt-level = 2
strip = true
lto = true
codegen-units = 1

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
